#!/bin/sh

# 默认开启 Wi-Fi (解除 disabled 状态)
uci set wireless.@wifi-device[0].disabled='0'

# 配置 HT2 Wi-Fi
uci set wireless.@wifi-iface[0].ssid='HT2-WiFi'
uci set wireless.@wifi-iface[0].key='12345678'
uci set wireless.@wifi-iface[0].encryption='psk2'

# 提交配置并应用
uci commit wireless
wifi reload

exit 0
